### ISSUE TITLE
How to use fastbind with HTTPS

### ISSUE THREAD

**Issue by acidvertigo** [gavv/httpexpect#21]
I'm tiring to test a https only server on fasthttp (http request will be redirect to https). I'm following the iris example.

My handler look like this:
```go
return httpexpect.WithConfig(httpexpect.Config{
		BaseURL: "https://example.com",
		Client: &http.Client{
			Transport: httpexpect.NewFastBinder(handler),
			Jar:       httpexpect.NewJar(),
		},
		Reporter: httpexpect.NewAssertReporter(t),
		Printers: []httpexpect.Printer{
		    httpexpect.NewCurlPrinter(t),
			httpexpect.NewDebugPrinter(t, true),
		},
	})
```

But when i use:
```go
	result := func() {
				e.GET("/").
					Expect().
					Status(http.StatusOK)
```

I get 10 redirect from http to https page and test fail.

On normal browser the redirect from http uri to https uri works well without cycling redirect.

Is possible to test fasthttp request on https?

**Comment by acidvertigo** [comment]
**UPDATE** I found that the code that redirect from http to HTTPS in default wrapper does not recognize the ssl connection:

```go
func (app *AppContext) DefaultWrapper(r fasthttp.RequestHandler) fasthttp.RequestHandler {
	return func(ctx *fasthttp.RequestCtx) {
	    if !ctx.IsTLS()  {
	       log.Info("not TLS")
		   ctx.Redirect("https://"+(string(ctx.Host())), 301)
		}
}
```
so also if httpexpect call the  correct https address the function ctx.IsTLS() is always false

**Comment by gavv** [comment]
Thanks for reporting, I'll look at it.

**Comment by gavv** [comment]
Automatic HTTP to HTTPS redirection works when using standard http transport, I've added a few tests (see commits linked above). So if it's an option, you could just use standard transport instead of binder.

There are two issues with current `Binder` and `FastBinder` implementation:

1. Currently there is no way to have separate handlers for HTTP and HTTPS with binders. Though, user can easily implement multiplexing binder that will map different protocol schemes to different http handlers.

2. Currently binders don't set TLS state for requests and responses, even if protocol scheme is https. To do it, we should mock `tls.Conn` and `tls.ConnectionState`.

@acidvertigo, two questions:

1. Do you need to use `Binder` or `FastBinder` for some reason, or using standard http transport is OK for you?

2. If we would mock TLS in binders, what do you expect from it? In particular, what do you expect to find in `tls.ConnectionState`: should we fill it with some fake data or make it settable by user or maybe we should deduce it from `tls.Config` provided by user?

**Comment by acidvertigo** [comment]
Thank you for your answer. I'm using fastbinder  because I'm developing an HTTPS only webapp with fasthttp and fasthttp-routing router.

I have tried to make this work changing the transport function with this code:
```go
func AppTester(t *testing.T) *httpexpect.Expect {

    tr := &http.Transport{
        TLSClientConfig: &tls.Config{InsecureSkipVerify: true},
    }	

	return httpexpect.WithConfig(httpexpect.Config{
		BaseURL: "https://mysite.org",
		Client: &http.Client{
			Transport: tr,
			Jar:       httpexpect.NewJar(),
		},
		Reporter: httpexpect.NewAssertReporter(t),
		Printers: []httpexpect.Printer{
		    httpexpect.NewCurlPrinter(t),
			httpexpect.NewDebugPrinter(t, true),
		},
	})
}
```

This so far works, but don't know if it is a good solution.

I think that a tls.Config solution can be a good choice.

**Comment by gavv** [comment]
> This so far works, but don't know if it is a good solution.

Usually yes. Actually you need binder only when you want to test separate HTTP handlers. If you're testing the whole application, standard HTTP transport is preferred, since this way tests are as close as possible to real-world scenario.

> I think that a tls.Config solution can be a good choice.

OK, so most likely we need to mock `tls.Conn` and `tls.ConnectionState` from `tls.Config`. Sounds reasonable. I'll think about it and keep this issue open.

**Comment by gavv** [comment]
@acidvertigo

> `BaseURL: "https://mysite.org",`

Just in case you don't know, you can use [`net/http/httptest`](https://golang.org/pkg/net/http/httptest/). This server runs your http or https handler on temporary port, and it's stoppable, which makes it very handy for tests. It's used in commits linked above.

**Comment by acidvertigo** [comment]
Thank you. I'll give a try.

**Comment by gavv** [comment]
I finally came up with a simple solution. Both `Binder` and `FastBinder` support mocking of `tls.ConnectionState` with a value provided by user. E.g., if `FastBinder.TLS` is set, `ctx.IsTLS()` will return true, and `ctx.TLSConnectionState()` will return `FastBinder.TLS`.

I'm closing this, but feel free to reopen.
