### ISSUE TITLE
Allow  JSON vendor content type

### ISSUE THREAD

**Issue by banux** [gavv/httpexpect#22]
Hi,

We use some JSON vendor content type like "application/vnd.odl.status.1-0+json".
But it failed because the getJSON check only for "application/json".

I can work on a PR if you consider it a bug.

Regards

**Comment by gavv** [comment]
Hi,

The feature sounds reasonable and pull requests are welcome!

Some thoughts.

Except `JSON`, we also have `JSONP`, `Form`, and `Text`. I think we should upgrade all of them for consistency.

I see four ways to implement this without breaking compatibility:

1. Add four new functions, e.g. `JSONWithContentType`, `FormWithContentType`, etc. But this clutters the API.

2. Add optional argument for content type to existing four functions. Actually, two arguments (media type and charset). I don't like this approach too, because it works only once. We'll not be able to add more optional arguments in future, because there are no named arguments in Go. And we'll need to use `interface{}` unless all arguments are of the same type.

3. Add single optional argument with a struct containing optional fields. In other words, emulate named arguments. This is a good approach by itself, but it adds some clutter and looks foreign for current httpexpect API. Also, I already have some plans for optional arguments in these functions, so I'd like to avoid this too.

4. Reuse existing `ContentType` method. If user calls `ContentType()` explicitly, `JSON` doesn't check content type. If not, `JSON` checks that content type is `application/json`. One limitation is that user should call `ContentType` before `JSON`. However, this approach seems better than previous ones.

So, currently I tend to think we need option `4.`, unless you can suggest something better.

**Comment by gavv** [comment]
Moved to v2. In v2 we can add this without bothering about compatibility.

**Comment by gavv** [comment]
I've added an optional ContentOpts argument to Text(), Form(), JSON(), and JSONP() methods, which allows to match non-default media type and/or charset.
