### ISSUE TITLE
Implement InList and NotInList methods

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#250]
Some matcher structs (Number, DateTime) have `InRange` method that checks that the value belongs to given range `[min; max]`.

Another convenient thing would be `InList` method, that checks that the value equals to one of the given values `a, b, c, ...`.

For example:

```go
array.Element(1).String().InList("green", "red")
```

We need to add `InList` and counterpart `NotInList` methods to the following structs:

* Value
* Object
* Array
* String
* Number
* Boolean (just for completeness)
* Duration
* DateTime

The new methods can use assertions of type AssertBelongs and AssertNotBelongs. Please place these methods after `InRange`, or after `Equal*` if there is no `InRange` for this struct.

Each method should have documentation comment with code example and be covered by a unit test. It would be also nice to demonstrate usage of InRange and InList in `_examples/fruits_test.go`.

**Comment by fahimbagar** [comment]
Hi @gavv, I have created PR for this issue: https://github.com/gavv/httpexpect/pull/256

Could you check it? and let me know how it goes

PS.
1. Since `AssertionList` rejects a single slice as a param, single array param in `InList` will behave like `IsEqual` and `NotInList` will behave like `NotEqual`. Added in https://github.com/gavv/httpexpect/commit/649ee8caf0e8c918aa9a2de8a8d6f6c5c3ec1cf7
https://github.com/gavv/httpexpect/blob/86f366a2d10b8a8ddd3cb1a9b2a5c00f37a1df68/assertion_validation.go#L186-L190

2. I'll update `_examples/fruits_test.go` if this PR is merged. Or do you have an alternative without modifying `go.mod` under `_examples`?

**Comment by gavv** [comment]
Thanks for pr! Will take a look shortly.

Re: PS

1. Let's just remove this check from assertion validation. It was useful euristics to catch bugs, but it's not working well with InList.

2. Yes, let's update examples separately, thanks.

**Comment by fahimbagar** [comment]
Addressed in https://github.com/gavv/httpexpect/pull/256/commits/40c6e50cc826924a245632406c46278e2c0f9a98.

Sure, thanks for your awesome repo as well :100:

**Comment by gavv** [comment]
Reopening after auto-close because we also need to update example.

**Comment by gavv** [comment]
Created follow-up issue: https://github.com/gavv/httpexpect/issues/261

**Comment by gavv** [comment]
I've tagged v2.11.0, which includes InList.

**Comment by fahimbagar** [comment]
@gavv, thanks for reviewing the PR.

I'll add an example along with this issue https://github.com/gavv/httpexpect/issues/251 if that's okay for you.

**Comment by gavv** [comment]
Great, thanks!! Please leave a comment there so that I can assign it to you.
