### ISSUE TITLE
Convert Number tests to table-driven style

### ISSUE THREAD

**Issue by gavv** [gavv/httpexpect#309]
Convert each subtest of the following tests to table-driven style:

* TestNumber_IsEqual
* TestNumber_InRange
* TestNumber_InList
* TestNumber_IsGreater
* TestNumber_IsLesser

`TestNumber_IsEqual/basic` can be used as a reference (it is already in desired style).

For subtests that do only a few checks (e.g. `TestNumber_IsEqual/invalid argument` has only two checks), instead of table we can use the same approach as in `TestNumber_IsInt/invalid argument`, where we create a fresh number for each check.

**Comment by gpjservais** [comment]
Hey @gavv, would I be able to work on this?

**Comment by gavv** [comment]
@gpjservais You're welcome, thank you :)

**Comment by gpjservais** [comment]
Hey @gavv, was there a reason for embedding subtests into another subtest named "basic" for `TestNumber_IsEqual/basic` when adding canonization and invalid arguments?

I was wondering if we could simplify things by sharing a general testing struct for tests and aliasing a function to perform the actual checks. I wasn't sure what would be preferred in terms of structuring the test.

In the example I included below, I kept with the example of `TestNumber_IsEqual/basic` and had subtest within larger groupings of subtests. Another option could be removing the names I've added to each test case & the `t.Run(name, func(t *testing.T) {...}` portion of _runSubtest_ so that it just runs each case as part of the larger subtest groupings of "basic", "canonization", and "invalid argument."
```Go
func TestNumber_IsLesser(t *testing.T) {
	type testSet struct {
		number    float64
		reference interface{}
		isLt      bool
		isLe      bool
	}

	runSubtest := func(cases map[string]testSet) {
		for name, instance := range cases {
			t.Run(name, func(t *testing.T) {
				reporter := newMockReporter(t)

				if instance.isLt {
					NewNumber(reporter, instance.number).Lt(instance.reference).
						chain.assertNotFailed(t)
				} else {
					NewNumber(reporter, instance.number).Lt(instance.reference).
						chain.assertFailed(t)
				}

				if instance.isLe {
					NewNumber(reporter, instance.number).Le(instance.reference).
						chain.assertNotFailed(t)
				} else {
					NewNumber(reporter, instance.number).Le(instance.reference).
						chain.assertFailed(t)
				}
			})
		}
	}

	t.Run("basic", func(t *testing.T) {
		basic_cases := map[string]testSet{
			"reference is greater": {number: 1234, reference: 1234 + 1, isLt: true, isLe: true},
			"reference is equal":   {number: 1234, reference: 1234, isLt: false, isLe: true},
			"reference is lesser":  {number: 1234, reference: 1234 - 1, isLt: false, isLe: false},
		}

		runSubtest(basic_cases)
	})

	t.Run("canonization", func(t *testing.T) {
		canonized_cases := map[string]testSet{
			"reference is int64":   {number: 1234, reference: int64(1234 + 1), isLt: true, isLe: true},
			"reference is float32": {number: 1234, reference: float32(1234 + 1), isLt: true, isLe: true},
		}

		runSubtest(canonized_cases)
	})

	t.Run("invalid argument", func(t *testing.T) {
		invalid_cases := map[string]testSet{
			"reference is a string": {number: 1234, reference: "NOT NUMBER", isLt: false, isLe: false},
		}

		runSubtest(invalid_cases)
	})
}
```

**Comment by gavv** [comment]
The idea was that for each method Xxx.Yyy we have a test TestXxx_Yyy and it has, among other things, subtests "canonization" and "invalid argument" (in case if it makes sense for Yyy).

This way tests are more unified and we can quickly check if some of the tests are missing those checks.

"basic" is just a name for everything else, and I think it's not a good name BTW (feel free to suggest a better one).

It would be nice to preserve "canonization" and "invalid argument" subtests. As for "basic", it's OK to split it into multiple subtests with meaningful names, or rename it to something else.

I think all subtests can have separate tables and separate loops.

Why:

* in `basic`, some checks should fail, and some succeed
* in `canonization`, it's ok to include only successful checks
* in `invalid argument`, all checks should fail

so it wouldn't be much code duplication, and on the other hand subtests will be more isolated (independent).

**Comment by gpjservais** [comment]
Okay, thanks for answering! I wanted to make sure before rewriting it all into a format like in my last comment.

I'll make sure to keep separate sections for "basic", "canonization", and "invalid argument" then. ☺️

For language, "basic" sounds fine. It could be renamed to "general" or "generic" if you had a preference since they're general/generic tests. I don't think it makes much of a difference, but I thought I'd throw the idea out there...

**Comment by gavv** [comment]
Yep, "basic" and "generic" are quite the same, so we can keep at as is for now.
